<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ru.ozon.uitp</groupId>
    <artifactId>uitp-edt-plugin.parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>uitp-edt-plugin.target</artifactId>
  <packaging>pom</packaging>

  <name>UITP E2E - target platform</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>target-maven-plugin</artifactId>
        <version>3.1.2</version>
        <configuration>
          <targetFile>default.target</targetFile>
          <attachPom>true</attachPom>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>target</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
